### ISSUE TITLE
[help] - testing module with new misp instance.

### ISSUE THREAD

**Issue by sjtrotter** [dfir-iris/iris-misp-module#2]
There is not much in the documentation supporting this module.

My main question is... what username does IRIS use to connect to MISP?

Is it the username of the person running the MISP insight? or... does it use their email address configured on their profile?

I just need to make sure whatever user is being used, is made within MISP, and that I give IRIS their API key...

**Comment by whikernel** [comment]
Hi @sjtrotter  

The configuration would be the following: 

```
{
    "name": "Whatever you want", 
    "type":"public", 
    "url": "You MISP URL",
    "key": "your misp user api key", 
    "ssl": False
}
```

The MISP API key being the one belonging to the user you want to connect with.. so the one of your choosing.  

Let me know if it helps 
Cheers

**Comment by sjtrotter** [comment]
Ah okay. I was reading over the documentation for MISP and saw that it doesn't really ask for username.

So... I can connect via cURL to pull from the MISP instance with the same settings I have set in the MISP module. I did have to pass a -k (to allow self-signed certs). I suspect that the IRIS module doesn't trust the MISP certificate, so that may be the reason I am running into issues.

Here's the relevant bit from the most recent DIM log from my last module run attempt:

```
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate
```

Do you have a suggestion on the best way to present the certificate to IRIS so that it accepts the MISP self-signed certificate?

**Comment by sjtrotter** [comment]
I found this: https://stackoverflow.com/questions/57362934/specify-cert-to-use-for-ssl-in-docker-compose-yml-file

seems to address the issue, but I'm not sure what I should do - which container is actually making the request? 

Is there some way to put this into the .env file so that it can persist across upgrades?

**Comment by whikernel** [comment]
@sjtrotter the `ssl` parameter in the JSON actually serve as an SSL verify switch. If you set it to true then the certificate is checked. If set to false, the certificate validity won't be checked.  
So you need to set it to false in your case.

**Comment by sjtrotter** [comment]
ah! alright, I'll try that. I assumed it was for telling iris to use ssl or not.

edit: worked! thanks again.
