### ISSUE TITLE
Documentation for MISP Reports

### ISSUE THREAD

**Issue by sjtrotter** [dfir-iris/iris-misp-module#3]
Hi there, I am looking for documentation on the report templates for the MISP reports. Something like the Jinja keywords to use etc, maybe an example template.

I tried looking thru the tree but I haven't been able to find one yet.

edit: I am looking at my instance and going thru the default template.

Quick question - Is there no way at this time to directly determine which fields returned from MISP are displayed to the page?

**Comment by whikernel** [comment]
Hi @sjtrotter 

The templating is working exactly as for the reporting templates in IRIS. It's also the same principle as the one in https://github.com/dfir-iris/iris-vt-module.  You can see all the fields returned from MISP with the default template. The variable `results` holds all the information. In your template you can then pick the information you want from this `results` object.   

Let me know if it helps.
Cheers
